import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { LeftNavbar } from './components/LeftNavbar';
import { Header } from './components/Header';
import { Content } from './components/Content';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Something Medical</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LeftNavbar />
      <Header />
      <Content />
    </div>
  )
}
